/*
 * Sample API
 *
 * # Features - Get users. - Create user. 
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClientError struct {
	Code string `json:"code,omitempty"`
	Type_ string `json:"type,omitempty"`
	Message string `json:"message,omitempty"`
	Errors []ClientErrorErrors `json:"errors,omitempty"`
}
