/*
 * Sample API
 *
 * # Features - Get users. - Create user. 
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SampleObjectUser struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
