/*
 * Sample API
 *
 * # Features - Get users. - Create user. 
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Review struct {
	Score int32 `json:"score,omitempty"`
	Comment string `json:"comment,omitempty"`
}
