/*
 * Sample API
 *
 * # Features - Get users. - Create user. 
 *
 * API version: 1.0.0
 * Contact: support@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClientErrorErrors struct {

	Field string `json:"field,omitempty"`

	Code string `json:"code,omitempty"`
}
